---
title: Assessing the Vanilla-bean Ice-cream Recipe from Chef Steps 🍦
author: Matthias Raess
date: '2018-01-22'
slug: assessing-the-vanilla-bean-ice-cream-recipe-from-chef-steps
draft: no
categories:
  - Cooking
tags:
  - Ice Cream
  - Dry Ice
---

You know it's about to get sciency in the kitchen when you have to pull out the good old dry-ice to churn your ice-cream base. Also you want to take some precautions because, remember, dry-ice (solid CO2) is COLD (-109.3 degrees F/-78.5 degrees C). I burned my finger when I was fishing it out of the ice-box at the store - it's still there, but recommend **not** doing that (it's like touching a hot pot or burner on your stove).

<!--more Keep reading-->

But whatever, on with the show. So the <a href="https://www.chefsteps.com/activities/vanilla-bean-ice-cream" target="_blank" rel="noopener">recipe in question</a> says to cook the ice cream base sous vide at 185F/85C for 60 minutes and to agitate the bag from time to time (like at least twice or so they say). Since egg yolks coagulate in between 149 and 158F, and only a much lower temperature is needed to pasteurize the eggs (<a href="https://eggsafety.org/egg-safety/" target="_blank" rel="noopener">@140F for 3.5 minutes</a>), I was suspicious and was expecting my ice cream base to scramble. However, the cooking process is not only for food safety, but even more to use the egg yolks as an emulsifier and gelling agent and thus use its hydrocolloid properties to create a thick custard. Traditionally, you'd stand next to your stove, constantly stirring your ice cream base in a bain-marie until it's nape (nah pay). However, the whole purpose of a sous vide machine is to free up time to make the accompanying <a href="https://pintsizedbaker.com/soft-caramel-sauce/">caramel sauce</a> (this one stays soft even on/in ice cream - I recommend heating it to 350F for consistent results).

Sure enough, after ~36 minutes, the custard looked scrambled and I pulled it out ready to discard it. <strong>HOWEVER</strong>, as it cooled down, it reconstituted and I was ultimately able to churn it into ice cream.


Take away: Agitate your bag way more often than they say in the recipe (only two times), reduce temperature to maybe 180F, and don't despair if it looks a little scrambled. Once, it cools down (in the ice bath), it should be okay. Two other bases I made were cooked shorter and at lower temps (160 and 170) for 20 and 30 minutes respectively. While the result was not bad, they didn't have the thickness of the original recipe and thus when churned bubbled up more and were a lot frothier overall.

Try it out!!